# This workflow is just for test

name: test workflow

on: 
  workflow_dispatch:
    inputs:
      tensorflow-alpa-branch-name:
        description: 'TensorFlow-alpa branch to test'
        required: true
        default: 'master'

jobs:
  test_job:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "TensorFlow Alpa branch: ${TF_BRANCH}"
          echo "Alpa branch: $ALPA_BRANCH"
      - env:
          TF_BRANCH: ${{ github.event.inputs.tensorflow-alpa-branch-name }}
          ALPA_BRANCH: ${{github.ref}}
